const actionTypes = Object.freeze({
    //app
    APP_STATUS_COMPLETE:"APP_STATUS_COMPLETE",

    //admin
    ADMIN_LOGIN_SUCCESS:"ADMIN_LOGIN_SUCCESS",
    ADMIN_REFRESH_TOKEN:"ADMIN_REFRESH_TOKEN",
    ADMIN_LOGIN_FAIL:"ADMIN_LOGIN_FAIL",
    ADMIN_PROCESS_LOGOUT:"PROCESS_LOGOUT",
    //user
    USER_LOGIN_SUCCESS:"USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL:"USER_LOGIN_FAIL",
    USER_PROCESS_LOGOUT:"USER_PROCESS_LOGOUT",

    MODAL_TOGGLE:"MODAL_TOGGLE",

    //Media
    MEDIA_LOAD:"MEDIA_LOAD",
})
export default actionTypes